# Generated by Django 2.2.1 on 2019-06-03 04:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profesor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=250)),
                ('matricula', models.IntegerField()),
                ('numeroTelefonico', models.IntegerField()),
                ('fechaNacimiento', models.DateField(default=django.utils.timezone.now)),
                ('materia', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('profesor', models.ForeignKey(on_delete=models.SET(-1), to='Profesor.Profesor')),
            ],
            options={
                'db_table': 'Estudiante',
            },
        ),
    ]
